version: "2"

run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errcheck
    - revive
    - gocritic
    - unconvert
    - prealloc
    - misspell
    - whitespace
    - gosec

  settings:
    revive:
      severity: warning
      confidence: 0.8
    misspell:
      locale: US

  exclusions:
    paths:
      - ^vendor/
      - ^testdata/

output:
  formats:
    text:
      print-issued-lines: true
      print-linter-name: true
  sort-order:
    - linter
    - file

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/ds-horizon/datagen