version: 2

run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true
  skip-dirs:
    - vendor
    - testdata

output:
  sort-results: true
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errcheck
    - revive
    - gocritic
    - unconvert
    - prealloc
    - misspell
    - whitespace
    - gosec

  settings:
    revive:
      severity: warning
      confidence: 0.8
    misspell:
      locale: US

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/yourorg/yourrepo


