codecov:
  require_ci_to_pass: yes

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: no
  after_n_builds: 1

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
