// Code generated by goyacc -l -o grammar.go grammar.y. DO NOT EDIT.
package parser

import __yyfmt__ "fmt"

import (
	"github.com/dream-horizon-org/datagen/codegen"
	"go/ast"
)

type yySymType struct {
	yys            int
	parsed         *codegen.DatagenParsed
	modelName      string
	fields         *ast.FieldList
	misc           string
	tags           map[string]string
	genFuns        []*codegen.GenFn
	serialiserFunc *codegen.SerialiserFunc
	calls          []*ast.CallExpr
	count          int
	str            string
	metadata       *codegen.Metadata
}

const MODEL = 57346
const FIELDS = 57347
const MISC = 57348
const METADATA = 57349
const GEN_FNS = 57350
const CALLS = 57351
const FN = 57352
const COUNT = 57353
const TAGS = 57354
const SERIALISER_FUNC = 57355
const L_BRACE = 57356
const R_BRACE = 57357
const L_PARENTHESIS = 57358
const R_PARENTHESIS = 57359
const COLON = 57360
const COUNT_INT = 57361
const MODEL_NAME = 57362
const FN_NAME = 57363
const FN_ARGS = 57364
const FN_BODY = 57365
const FIELDS_BODY = 57366
const MISC_BODY = 57367
const TAGS_BODY = 57368
const CALLS_BODY = 57369

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"MODEL",
	"FIELDS",
	"MISC",
	"METADATA",
	"GEN_FNS",
	"CALLS",
	"FN",
	"COUNT",
	"TAGS",
	"SERIALISER_FUNC",
	"L_BRACE",
	"R_BRACE",
	"L_PARENTHESIS",
	"R_PARENTHESIS",
	"COLON",
	"COUNT_INT",
	"MODEL_NAME",
	"FN_NAME",
	"FN_ARGS",
	"FN_BODY",
	"FIELDS_BODY",
	"MISC_BODY",
	"TAGS_BODY",
	"CALLS_BODY",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 69

var yyAct = [...]int8{
	43, 36, 42, 61, 35, 33, 66, 45, 62, 55,
	4, 57, 52, 51, 13, 14, 15, 17, 16, 6,
	64, 59, 18, 67, 44, 63, 56, 20, 21, 22,
	23, 24, 25, 54, 53, 48, 47, 46, 19, 49,
	50, 65, 58, 31, 30, 29, 28, 27, 26, 5,
	39, 40, 2, 1, 41, 60, 34, 32, 37, 10,
	12, 11, 38, 9, 8, 7, 3, 0, 68,
}

var yyPact = [...]int16{
	48, -1000, -10, 35, -1000, 9, 23, 9, 9, 9,
	9, 9, 9, 34, 33, 32, 31, 30, 29, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -19, -21, 39, -25,
	14, -16, 22, -1000, 21, -1000, 20, 39, 39, -5,
	-6, 19, -1000, 18, -12, 11, -1000, -1000, -1000, -1000,
	-1000, -8, 28, -1000, -1000, 5, -1000, -1000, -23, -14,
	10, -1000, 3, -1000, 27, -17, 8, 14, -1000,
}

var yyPgo = [...]int8{
	0, 66, 19, 65, 64, 63, 1, 62, 61, 0,
	60, 59, 58, 57, 56, 55, 54, 53,
}

var yyR1 = [...]int8{
	0, 17, 1, 2, 2, 2, 2, 2, 2, 2,
	3, 13, 4, 14, 5, 6, 6, 6, 12, 7,
	15, 11, 16, 8, 9, 9, 10,
}

var yyR2 = [...]int8{
	0, 5, 1, 2, 2, 2, 2, 2, 2, 0,
	4, 1, 4, 1, 4, 2, 2, 0, 3, 5,
	1, 4, 1, 4, 9, 0, 4,
}

var yyChk = [...]int16{
	-1000, -17, 4, -1, 20, 14, -2, -3, -4, -5,
	-11, -8, -10, 5, 6, 7, 9, 8, 13, 15,
	-2, -2, -2, -2, -2, -2, 14, 14, 14, 14,
	14, 14, -13, 24, -14, 25, -6, -12, -7, 11,
	12, -16, 27, -9, 10, 23, 15, 15, 15, -6,
	-6, 18, 18, 15, 15, 21, 15, 19, 14, 16,
	-15, 26, 22, 15, 17, 14, 23, 15, -9,
}

var yyDef = [...]int8{
	0, -2, 0, 0, 2, 9, 0, 9, 9, 9,
	9, 9, 9, 0, 0, 0, 0, 0, 0, 1,
	3, 4, 5, 6, 7, 8, 0, 0, 17, 0,
	25, 0, 0, 11, 0, 13, 0, 17, 17, 0,
	0, 0, 22, 0, 0, 0, 10, 12, 14, 15,
	16, 0, 0, 21, 23, 0, 26, 18, 0, 0,
	0, 20, 0, 19, 0, 0, 0, 25, 24,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.modelName = yyDollar[1].str
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*lex).parsed.Fields = yyDollar[1].fields
			yyVAL.parsed = yylex.(*lex).parsed
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*lex).parsed.Misc = yyDollar[1].misc
			yyVAL.parsed = yylex.(*lex).parsed
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*lex).parsed.Metadata = yyDollar[1].metadata
			yyVAL.parsed = yylex.(*lex).parsed
		}
	case 6:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*lex).parsed.Calls = yyDollar[1].calls
			yyVAL.parsed = yylex.(*lex).parsed
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*lex).parsed.GenFuns = yyDollar[1].genFuns
			yyVAL.parsed = yylex.(*lex).parsed
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*lex).parsed.SerialiserFunc = yyDollar[1].serialiserFunc
			yyVAL.parsed = yylex.(*lex).parsed
		}
	case 9:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.parsed = yylex.(*lex).parsed
		}
	case 10:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.fields = yylex.(*lex).parse_fields(yyDollar[3].str)
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = yyDollar[1].str
		}
	case 12:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.misc = yylex.(*lex).parse_misc(yyDollar[3].str)
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = yyDollar[1].str
		}
	case 14:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.metadata = yyDollar[3].metadata
		}
	case 15:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			if yyDollar[2].metadata == nil {
				yyDollar[2].metadata = &codegen.Metadata{}
			}
			yyDollar[2].metadata.Count = yyDollar[1].count
			yyVAL.metadata = yyDollar[2].metadata
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			if yyDollar[2].metadata == nil {
				yyDollar[2].metadata = &codegen.Metadata{}
			}
			yyDollar[2].metadata.Tags = yyDollar[1].tags
			yyVAL.metadata = yyDollar[2].metadata
		}
	case 17:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.count = yyDollar[3].count
		}
	case 19:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.tags = yylex.(*lex).parse_tags(yyDollar[4].str)
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = yyDollar[1].str
		}
	case 21:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.calls = yylex.(*lex).parse_calls(yyDollar[3].str)
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = yyDollar[1].str
		}
	case 23:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.genFuns = yyDollar[3].genFuns
		}
	case 24:
		yyDollar = yyS[yypt-9 : yypt+1]
		{
			yylex.(*lex).add_gen_fn(yyDollar[2].str, yyDollar[4].str, yyDollar[7].str)
			yyVAL.genFuns = yylex.(*lex).parsed.GenFuns
		}
	case 25:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.genFuns = yylex.(*lex).parsed.GenFuns
		}
	case 26:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.serialiserFunc = yylex.(*lex).add_serialiser_fn(yyDollar[3].str)
		}
	}
	goto yystack /* stack new state and value */
}
